# Generated by Django 6.0.5 on 2026-05-18 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Tenant school — blank for super admin only', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='schools.school'),
        ),
    ]
