# Generated by Django 6.0.5 on 2026-06-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_on_messages',
            field=models.BooleanField(default=True, help_text='Send email when a new school message reply arrives.'),
        ),
    ]
