# Generated by Django 6.0.5 on 2026-06-09 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuranSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_number', models.PositiveSmallIntegerField()),
                ('surah_name', models.CharField(max_length=80)),
                ('ayah_start', models.PositiveSmallIntegerField()),
                ('ayah_end', models.PositiveSmallIntegerField()),
                ('ayah_text', models.TextField(help_text='Displayed mushaf text for the selected ayah range.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='draft', max_length=20)),
                ('student_audio', models.FileField(blank=True, upload_to='quran/recitations/')),
                ('teacher_feedback_audio', models.FileField(blank=True, upload_to='quran/feedback/')),
                ('teacher_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quran_sessions', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quran_sessions', to='students.studentprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quran_sessions', to='teachers.teacherprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuranAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayah_number', models.PositiveSmallIntegerField()),
                ('tag', models.CharField(choices=[('tajweed', 'Tajweed'), ('memorisation', 'Memorisation'), ('fluency', 'Fluency')], max_length=20)),
                ('timestamp_seconds', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quran_annotations', to='teachers.teacherprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='quran.quransession')),
            ],
            options={
                'ordering': ['timestamp_seconds', 'ayah_number'],
            },
        ),
    ]
