# Generated by Django 6.0.5 on 2026-05-30 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('track', models.CharField(choices=[('hifz', 'Hifz'), ('alimiyah', 'Alimiyah'), ('general', 'General')], default='general', max_length=20)),
                ('code', models.CharField(blank=True, help_text='Short code e.g. HIFZ-1', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_led', to='teachers.teacherprofile')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schools.school')),
            ],
            options={
                'ordering': ['track', 'name'],
                'unique_together': {('school', 'name')},
            },
        ),
    ]
