# Generated by Django 6.0.5 on 2026-05-18 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='teachers.teacherprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='classgroup',
            unique_together={('school', 'name')},
        ),
    ]
