# Generated by Django 6.0.5 on 2026-05-30 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='timetable_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='timetable.timetableslot'),
        ),
        migrations.AddField(
            model_name='attendancemark',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='attendance.attendancesession'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('class_group', 'session_date')},
        ),
        migrations.AlterUniqueTogether(
            name='attendancemark',
            unique_together={('session', 'student')},
        ),
    ]
